-- select * FROM EMP_PROJECT .DEPARTMENT;
-- SELECT * FROM emp_project.employee;
-- SELECT * FROM emp_project.PROJECT;
SELECT * FROM emp_project.employee_project;
-- USING 3  CLAUSES
SELECT * FROM emp_project.EMPLOYEE WHERE SALARY <= 55000;
SELECT * FROM emp_project.PROJECT WHERE DEPARTMENT_ID = 105;
SELECT * FROM EMP_PROJECT.employee_project WHERE PROJECT_ID = 207;
select SALARY FROM emp_project.employee;
-- USING DISTINCT
SELECT DISTINCT SALARY FROM EMPLOYEE;
SELECT DISTINCT HIREDATE, SALARY, DEPARTMENT_ID
FROM EMPLOYEE;
SELECT DISTINCT PROJECT_ID FROM EMPLOYEE_PROJECT;
-- USING ALIAS
SELECT FIRST_NAME  "NAME"
FROM EMPLOYEE;
SELECT ROLE AS "JOB" FROM EMPLOYEE_PROJECT;
SELECT DEPARTMENT_NAME AS "DNAME" FROM DEPARTMENT;
SELECT PROJECT_NAME AS "PROJECT" FROM PROJECT;
-- USING ARITHMETIC OPERATOR
SELECT SALARY *12 AS "ANNUAL_SALARY"
FROM employee
WHERE DEPARTMENT_ID = 103;
SELECT SALARY/4 AS "WEEKLY_ SALARY"
FROM EMPLOYEE;
SELECT SALARY + SALARY * 12/100
FROM EMPLOYEE;
SELECT SALARY - 10000 
FROM EMPLOYEE
WHERE DEPARTMENT_ID = 103;
-- using Relational operators
SELECT * FROM EMPLOYEE
WHERE SALARY >= 70000;
SELECT * FROM EMPLOYEE
WHERE HIREDATE <= '2017-01-01';
SELECT * FROM EMPLOYEE
WHERE MANAGER_ID <> 3;
SELECT EMPLOYEE.*,SALARY + SALARY * 10/100
FROM EMPLOYEE
WHERE SALARY < 60000;
SELECT * FROM EMPLOYEE 
WHERE SALARY > 70000;
 -- using concatenation operator
 select CONCAT('MR.',FIRST_NAME,CONCAT(LAST_NAME)) FROM EMPLOYEE;
 -- USING LOGICAL OPERATOR 'AND'
 SELECT * FROM EMPLOYEE  WHERE SALARY > 60000 AND DEPARTMENT_ID = 104;
 SELECT * FROM PROJECT WHERE START_DATE > '2021-01-01' AND END_DATE < '2023-01-01';
 SELECT * FROM EMPLOYEE_PROJECT WHERE role = 'DEVELOPER' and PROJECT_ID = 204;
 -- USING LOGICAL OPERATOR 'OR'
 SELECT * FROM EMPLOYEE WHERE HIRE_DATE < '2018-01-01' OR SALARY < 70000;
 SELECT * FROM PROJECT WHERE PROJECT_ID = 201 OR DEPARTMENT_ID = 101;
 SELECT * FROM EMPLOYEE_PROJECT  WHERE EMPLOYEE_ID = 4 OR PROJECT_ID = 204;
 SELECT * FROM DEPARTMENT WHERE  DEPARTMENT_ID = 102 OR DEPARTMENT_NAME = 'IT';
 -- USING LOGICAL OPERATOR 'NOT'
 SELECT * FROM EMPLOYEE WHERE NOT SALARY = 70000;
 SELECT * FROM PROJECT WHERE NOT DEPARTMENT_ID = 103;
 SELECT * FROM EMPLOYEE_PROJECT WHERE NOT ROLE = 'DEVELOPER';
 SELECT * FROM DEPARTMENT WHERE NOT DEPARTMENT_ID = 104;
 
-- USING SPECIAL OPERATOR 'IS','IS NOT'
SELECT * FROM EMPLOYEE WHERE SALARY IS NOT NULL;
SELECT * FROM EMPLOYEE WHERE SALARY IS NULL;
SELECT * FROM PROJECT WHERE PROJECT_NAME IS NULL;

-- USING 'IN','NOT IN' OPERATOR 
SELECT * FROM  EMPLOYEE WHERE SALARY IN (60000,65000,70000,75000);
SELECT * FROM EMPLOYEE WHERE DEPARTMENT_ID NOT IN (101,103,105);
SELECT * FROM PROJECT WHERE DEPARTMENT_ID IN (101,105);
SELECT * FROM PROJECT WHERE DEPARTMENT_ID NOT IN (101,105);
SELECT * FROM EMPLOYEE_PROJECT WHERE ROLE IN ('DEVELOPER','MANAGER');
SELECT * FROM EMPLOYEE_PROJECT WHERE ROLE NOT IN ('DEVELOPER','MANAGER');
-- USING 'BETWEEN' OPERATOR
SELECT * FROM EMPLOYEE WHERE SALARY BETWEEN 55000 AND 65000;
SELECT * FROM EMPLOYEE WHERE SALARY NOT BETWEEN 55000 AND 65000;
SELECT * FROM PROJECT WHERE START_DATE BETWEEN '2021-01-01' AND '2022-01-01';
SELECT * FROM PROJECT WHERE START_DATE NOT BETWEEN '2021-01-01' AND '2022-01-01';
SELECT * FROM DEPARTMENT WHERE DEPARTMENT_ID BETWEEN 101 AND 104;
-- USING 'LIKE' AND 'NOT LIKE' OPERATOR
SELECT * FROM EMPLOYEE WHERE FIRST_NAME LIKE '%E';
SELECT * FROM EMPLOYEE WHERE FIRST_NAME LIKE 'S%';
SELECT * FROM EMPLOYEE WHERE FIRST_NAME LIKE '%LL%';
SELECT * FROM EMPLOYEE WHERE LAST_NAME LIKE 'E____';
SELECT * FROM EMPLOYEE WHERE SALARY LIKE '55___';







